services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}
    volumes:
      - mongo:/data/db

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_USER=${ROOT_USERNAME}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
    volumes:
      - mariadb:/var/lib/mysql

  app:
    depends_on:
      - mongo
    build: app
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync+restart
          path: app/src
          target: /app/src
        - action: rebuild
          path: app/Dockerfile
        - action: rebuild
          path: app/requirements.txt

volumes:
  mongo:
  mariadb:
