# create compose for python
version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db

  app:
    depends_on:
      - mongo
    build: app
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync+restart
          path: app/src
          target: /app/src
        - action: rebuild
          path: app/Dockerfile
        - action: rebuild
          path: app/requirements.txt

volumes:
  mongo:
